// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activate запускает активацию: slmgr /ato
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function Activate() {
    return $Call.ByID(2796686707).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CheckDetails выполняет подробный отчет о лицензии: slmgr /dli
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function CheckDetails() {
    return $Call.ByID(4235146560).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CheckStatus выполняет проверку срока окончания лицензии: slmgr /xpr
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function CheckStatus() {
    return $Call.ByID(1093391372).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * FullActivation выполняет полный цикл активации
 * @param {string} key
 * @param {string} server
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function FullActivation(key, server) {
    return $Call.ByID(3852226595, key, server).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetHardwareSpecs возвращает подробные аппаратные характеристики ПК
 * @returns {$CancellablePromise<$models.HardwareSpecs>}
 */
export function GetHardwareSpecs() {
    return $Call.ByID(838341050).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSystemInfo возвращает данные об ОС и статусе прав администратора
 * @returns {$CancellablePromise<$models.SystemInfo>}
 */
export function GetSystemInfo() {
    return $Call.ByID(1936959035).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * InstallKey выполняет команду из promt.txt: slmgr /ipk <KEY>
 * @param {string} key
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function InstallKey(key) {
    return $Call.ByID(813523672, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * PrintSpecsToConsole выводит характеристики ПК прямо в консоль приложения
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function PrintSpecsToConsole() {
    return $Call.ByID(2596923147).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Rearm выполняет сброс таймера активации: slmgr /rearm
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function Rearm() {
    return $Call.ByID(2301272991).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RelaunchAsAdmin перезапускает приложение с повышением UAC
 * @returns {$CancellablePromise<boolean>}
 */
export function RelaunchAsAdmin() {
    return $Call.ByID(3246853911);
}

/**
 * ResetKey выполняет удаление ключа и очистку из реестра: slmgr /upk + slmgr /cpky
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function ResetKey() {
    return $Call.ByID(4105882876).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(671577681, app);
}

/**
 * SetKMSServer задает KMS-сервер: slmgr /skms <SERVER>
 * @param {string} server
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function SetKMSServer(server) {
    return $Call.ByID(147289408, server).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CommandResult.createFrom;
const $$createType1 = $models.HardwareSpecs.createFrom;
const $$createType2 = $models.SystemInfo.createFrom;
