// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CommandResult {
    /**
     * Creates a new CommandResult instance.
     * @param {Partial<CommandResult>} [$$source = {}] - The source object to create the CommandResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult(/** @type {Partial<CommandResult>} */($$parsedSource));
    }
}

export class DiskInfo {
    /**
     * Creates a new DiskInfo instance.
     * @param {Partial<DiskInfo>} [$$source = {}] - The source object to create the DiskInfo.
     */
    constructor($$source = {}) {
        if (!("letter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["letter"] = "";
        }
        if (!("totalGb" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["totalGb"] = "";
        }
        if (!("freeGb" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["freeGb"] = "";
        }
        if (!("usedGb" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["usedGb"] = "";
        }
        if (!("percentUsed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percentUsed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskInfo(/** @type {Partial<DiskInfo>} */($$parsedSource));
    }
}

export class HardwareSpecs {
    /**
     * Creates a new HardwareSpecs instance.
     * @param {Partial<HardwareSpecs>} [$$source = {}] - The source object to create the HardwareSpecs.
     */
    constructor($$source = {}) {
        if (!("cpuName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cpuName"] = "";
        }
        if (!("cpuCores" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpuCores"] = 0;
        }
        if (!("totalRam" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["totalRam"] = "";
        }
        if (!("availRam" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["availRam"] = "";
        }
        if (!("usedRam" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["usedRam"] = "";
        }
        if (!("ramPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ramPercent"] = 0;
        }
        if (!("gpus" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["gpus"] = [];
        }
        if (!("motherboard" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["motherboard"] = "";
        }
        if (!("biosInfo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["biosInfo"] = "";
        }
        if (!("disks" in $$source)) {
            /**
             * @member
             * @type {DiskInfo[]}
             */
            this["disks"] = [];
        }
        if (!("osName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["osName"] = "";
        }
        if (!("osVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["osVersion"] = "";
        }
        if (!("osBuild" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["osBuild"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("computerName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["computerName"] = "";
        }
        if (!("userName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userName"] = "";
        }
        if (!("uptime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uptime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HardwareSpecs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HardwareSpecs}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("gpus" in $$parsedSource) {
            $$parsedSource["gpus"] = $$createField6_0($$parsedSource["gpus"]);
        }
        if ("disks" in $$parsedSource) {
            $$parsedSource["disks"] = $$createField9_0($$parsedSource["disks"]);
        }
        return new HardwareSpecs(/** @type {Partial<HardwareSpecs>} */($$parsedSource));
    }
}

export class SystemInfo {
    /**
     * Creates a new SystemInfo instance.
     * @param {Partial<SystemInfo>} [$$source = {}] - The source object to create the SystemInfo.
     */
    constructor($$source = {}) {
        if (!("osName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["osName"] = "";
        }
        if (!("displayVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayVersion"] = "";
        }
        if (!("buildNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildNumber"] = "";
        }
        if (!("editionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["editionId"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("isAdmin" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isAdmin"] = false;
        }
        if (!("defaultKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultKey"] = "";
        }
        if (!("defaultServer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultServer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemInfo(/** @type {Partial<SystemInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DiskInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
